[package]
name = "taiko"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
bytemuck = { version = "1.13.1", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
lyon = "1.0.1"
nom = "7.1.3"
rand = "0.8.5"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
wgpu = "0.16.0"
winit = "0.28.3"
