[package]
name = "taiko"
authors = ["luna borella <ulfrthewolf@gmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ab_glyph = "0.2.21"
anyhow = "1.0.70"
bytemuck = { version = "1.13.1", features = ["derive"] }
egui = "0.22.0"
egui-wgpu = "0.22.0"
egui_winit_platform = "0.19.0"
env_logger = "0.10.0"
image = "0.24.6"
itertools = "0.10.5"
kira = "0.7.3"
lazy_static = "1.4.0"
log = "0.4.17"
lookahead = "0.1.0"
lyon = "1.0.1"
nom = "7.1.3"
num-derive = "0.3.3"
num-traits = "0.2.15"
rand = "0.8.5"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
wgpu = "0.16.0"
wgpu_text = "0.8"
winit = "0.28.3"
